{{ if eq .Values.nodeType "rpc" -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.ws.domain }}-tls
spec:
  dnsNames:
  - {{ .Values.ingress.ws.domain }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: {{ .Values.ingress.ws.domain }}-tls
{{ end }}
