{{ if eq .Values.nodeType "rpc" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "openNodeChart.workloadName" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/limit-rps: {{ .Values.ingress.ws.limitRPS }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.ingress.ws.proxyReadTimeout }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{ .Values.ingress.ws.proxySendTimeout }}
spec:
  tls:
  - hosts:
      - {{ .Values.ingress.domain }}
    secretName: {{ .Values.ingress.domain }}-tls
  rules:
  - host: {{ .Values.ingress.domain }}
    http:
      paths:
      - path: /public-ws
        pathType: Prefix
        backend:
          service:
            name: {{ include "openNodeChart.workloadName" . }}-rpc
            port:
              number: {{ .Values.port.rpc.ws }}
      - path: /public-rpc
        pathType: Prefix
        backend:
          service:
            name: {{ include "openNodeChart.workloadName" . }}-rpc
            port:
              number: {{ .Values.port.rpc.http }}
{{ end }}