{{- if eq .Values.nodeType "rpc" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openNodeChart.workloadName" . }}-rpc
  labels:
    app: open-node
    node-type: {{ .Values.nodeType }}
spec:
  ports:
  - name: http-rpc
    port: {{ .Values.port.rpc.http }}
  - name: websocket-rpc
    port: {{ .Values.port.rpc.ws }}
  selector:
    app: open-node
    node-type: {{ .Values.nodeType }}
{{- end }}
