{{ if .Values.certmanager.createCertIssuer -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: {{ .Values.letsencrypt.serverURL }}
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.cloudflare.email }}
          apiKeySecretRef:
            name: cloudflare-credentials
            key: api-key
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
  # Namespace where cert-manager runs in.
  namespace: {{ .Values.certmanager.namespace }}
data:
  api-key: {{ .Values.cloudflare.apiKey | b64enc }}
type: Opaque
{{ end }}
