# nodeType is the type of this open node instance, should be one of full, rpc, bootstrap, collator
nodeType: full

replicaCount: 1

image:
  repository: phalanetwork/khala-dev-node
  pullPolicy: IfNotPresent
  tag: latest-healthcheck

command: 
- /root/khala-node

args:
  para:
  - --chain=/root/thala-local-2004-raw.chain_spec.json
  - --pruning=archive
  - --state-cache-size=671088640
  - --db-cache=2048
  - --max-runtime-instances=16
  relay:
  - --chain=/root/rococo-local-raw.chain_spec.json
  - --pruning=256
  - --state-cache-size=671088640
  - --db-cache=2048
  - --max-runtime-instances=16

dataPath: /data

dataVolume:
  storageClassName: ""
  initialSize: 20Gi

port:
  p2p:
    para: 30333
    relay: 30334
  rpc:
    http: 9933
    ws: 9944

ingress:
  http:
    domain: ""
    # Number of requests accepted from a given IP each second, for rate limiting purpose.
    limitRPS: "10"
    proxyReadTimeout: "3600"
    proxySendTimeout: "3600"
  ws:
    # The domain name of websocket RPC ingress forwarding rule.
    domain: ""
    # Number of requests accepted from a given IP each second, for rate limiting purpose.
    limitRPS: "10"
    # Read/Send timeout settings are critical to websocket service. 
    proxyReadTimeout: "3600"
    proxySendTimeout: "3600"

livenessProbe:
  failureThreshold: 3
  exec:
    command:
    - curl
    - -f
    - -H
    - "Content-Type: application/json"
    - -d
    - '{"id":1, "jsonrpc":"2.0", "method": "system_health"}'
    - http://localhost:9933/
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  failureThreshold: 3
  exec:
    command:
    - sh
    - /root/health.sh
  initialDelaySeconds: 10
  periodSeconds: 10

resources:
  requests:
    cpu: "2"
    memory: "2Gi"
  limits:
    cpu: "2"
    memory: "2Gi"

podAnnotations: {}

imagePullSecrets: []

podSecurityContext: {}

securityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}
